name: "Geometrification"
title: "Geometrification"
description: "A blog about geometry from different points of view"
logo: '\Users\USER\Desktop\Blog\Blow up image.png'
# URL of your avatar or profile pic (you could use your GitHub profile pic)
favicon: '\Users\USER\Desktop\Blog\Blow up image.png'
baseurl: ''
google_analytics: ''
disqus: ''
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

#
# Flags below are optional
#

# Your website URL (e.g. https://forever-jekyll.github.io or https://forever-jekyll.com)
# Used for Sitemap.xml and your RSS feed
